### ISSUE TITLE
Create a CatchAll ExceptionsFilter

### ISSUE THREAD

**Issue by pragmaticivan** [pragmaticivan/nestjs-otel#11]
Register a Counter:

```
name: 'http_exceptions',
labels : ['method', 'status', 'path'],
```

Support config: `withExceptionFilter`

It should conditionally replace `provide: APP_FILTER,` if enabled.

**Comment by issackr** [comment]
Thanks for the great work!
might be nice to support GraphQL from the beginning:
https://github.com/digikare/nestjs-prom/issues/47

**Comment by pragmaticivan** [comment]
Nice! Will keep that in mind for sure. Same for supporting Fastify.

**Comment by pragmaticivan** [comment]
This is generally introspected from opentelemetry auto instrumentation already.
