### ISSUE TITLE
otel/opentelemetry-collector-dev:latest no longer ships with extensions

### ISSUE THREAD

**Issue by RobertLowe** [pragmaticivan/nestjs-otel#149]
`otel/opentelemetry-collector-dev:latest` no longer ships with extensions

```
collector_1     | Error: cannot load configuration: unknown extensions type "health_check" for health_check
collector_1     | 2021/11/14 11:40:03 collector server run finished with error: cannot load configuration: unknown extensions type "health_check" for health_check
collector_1 exited with code 1
```

https://github.com/pragmaticivan/nestjs-otel/blob/main/examples/nestjs-prom-grafana-tempo-otel-collector/docker-compose.yml#L76

The last working image I found was:  `otel/opentelemetry-collector-dev:20ac40ae3c535195341bdcefef07f98a1ecedcf1`

You can see here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#v0340-beta it was moved to `contrib`

**Comment by pragmaticivan** [comment]
Howdy! I've removed that sample from this repo. Moved to my username profile but will need to spend the time with updating everything.
