### ISSUE TITLE
Nestjs jaeger trace with dns lookup

### ISSUE THREAD

**Issue by SunilManthenaG01** [pragmaticivan/nestjs-otel#150]
Hi, I am using this library for tracing with open telemetry and jaeger exporter. 
For the incoming request to the nestjs service I see in jaeger, it is reporting as DNS lookup rather than an HTTP request. Is there anything wrong with my configuration?

const otelSDK = new NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: 'nest-otel-lib',
  }),
  spanProcessor: new BatchSpanProcessor(new JaegerExporter()),
  instrumentations: [
    getNodeAutoInstrumentations(),
  ],
});
const bootstrap = async () => {
  otelSDK.start();
  const { appDispatcher } = await import('wms-bff-core');
  const { AppModule } = await import('./app.module');
  await appDispatcher(AppModule);
};
bootstrap();

Here is the sample of the trace in Jaeger.

![image](https://user-images.githubusercontent.com/53482186/142023286-41bbcea0-9553-4a67-b057-d6bca3268f58.png)

**Comment by pragmaticivan** [comment]
Hi @SunilManthenaG01 Otel instrumentation `always` should come before any import. Because you are putting the code in the same file, you might not get the behavior you expect. In the examples the `trace.ts` code is in a different file and is the first to be imported for that reason.

**Comment by SunilManthenaG01** [comment]
@pragmaticivan  Thank you for your response.

I tried that way. I created a trace.ts file and imported that file first but still the same result.

main.ts
import otelSDK from './trace';
import { resolve } from 'path';
process.env.APP_ROOT_DIR = resolve(`${__dirname}`);

const bootstrap = async () => {
  await otelSDK.start();
  const { appDispatcher } = await import('wms-bff-core');
  const { AppModule } = await import('./app.module');
  await appDispatcher(AppModule);
};
bootstrap();


trace.ts file


const otelSDK = new NodeSDK({
    resource: new Resource({
        [SemanticResourceAttributes.SERVICE_NAME]: 'manin-test',
    }),
    spanProcessor: new BatchSpanProcessor(new JaegerExporter()),
    instrumentations: [getNodeAutoInstrumentations()],
});
export default otelSDK;

**Comment by SunilManthenaG01** [comment]
After some debugging, I see the issue is because I am using spdy listening on h2 protocol. If I switch that to HTTP 1.1 I can see the traces in jaeger but if the server protocol is h2 I can not see the traces.

Do we need to change anything if we need to make the trace work for h2 protocol?

**Comment by pragmaticivan** [comment]
I think h2 requires keys. At this point, I would recommend using an open telemetry-collector instead to receive your tracing and metrics. It can redirect things into Jaeger. I'm not super familiar with sending it directly to Jaeger in a production env. In my context it has TLS and it's required to be used.

**Comment by pragmaticivan** [comment]
Btw, the part that actually sends the trace comes from using nodejs-sdk (open telemetry). Closing this issue for now as you found a workaround.
