### ISSUE TITLE
TraceService returning the wrong span

### ISSUE THREAD

**Issue by IamBlueSlime** [pragmaticivan/nestjs-otel#154]
Hi,

I'm a little confused with the documentation of the interaction between the `@Span` decorator and the `TraceService`. From what I've understood, `TraceService.getSpan` function returns the latest opened span of the currently active context. This means that, with the following snippet, the log should output `TestService.myHelper`.

```ts
export class TestService {
  constructor(private readonly traceService: TraceService) {}

  @Span()
  myHelper() {
    const span = this.traceService.getSpan();
    console.log((span as any).name); // Not a ReadableSpan, hack for test purpose
  }
}
```

My issue here is that it does not work as expected:

1. In the context of an HTTP request, the span returned has `GET /test` as name, i.e. the span wrapping the `TestService.myHelper` span. Please note that the `@Span` decorator works as expected because the span is correctly opened and closed, the behavior mismatch seems to be related to the `TraceService`.
2. In a raw context, for instance calling the snippet above from a `onModuleInit()` function in any class, the span returned by the `TraceService` is undefined. Which seems legitimate because the (1) point indicate that the service does not return the span opened by `@Span`.

<details>
<summary>Controller's code</summary>

```ts
@Controller()
export class TestController {
  constructor(private readonly svc: TestService) {}

  @Get('test')
  handle(): void {
    this.svc.myHelper();
  }
}
```

</details>

<details>
<summary>Module's code</summary>

```ts
@Module({
  imports: [
    OpenTelemetryModule.forRoot({
      metrics: {
        hostMetrics: true,
        defaultMetrics: true,
        apiMetrics: {
          enable: true,
        },
      },
    }),
    CommonModule,
  ],
  providers: [TestService],
  controllers: [TestController],
})
export class RootModule {
  constructor(private readonly svc: TestService) {}

  onModuleInit() {
    this.svc.myHelper();
  }
}
```

</details>

My question here is: is that the behavior expected? From the documentation in the README, it seems that it's a bug. I've provided the minimal code to reproduce, its fairly simple to reproduce :)

Thanks!

**Comment by mentos1386** [comment]
Might be related with #165.

**Comment by pragmaticivan** [comment]
Howdy! I will take a look at it today, sorry about the delay!
