### ISSUE TITLE
Question of the span decorator

### ISSUE THREAD

**Issue by blastZ** [pragmaticivan/nestjs-otel#165]
Hi, I am confused with this code, why `context.with` use `context.active` ? 

In my opinion it will cause `parentSpan` always be the `rootSpan` without `context.with` in the code.

```ts
const currentSpan = trace.getSpan(context.active());
const tracer = trace.getTracer('default')

return context.with(trace.setSpan(context.active(), currentSpan), () => {
  // ...
});
```

I think it should be

```ts
const tracer = trace.getTracer('default')
const span = tracer.startSpan(
  name || `${target.constructor.name}.${propertyKey}`,
);

return context.with(trace.setSpan(context.active(), span), () => {
  // ...
});
```

For example

```ts
class Test {
  @Span()
  f1() {
    // ...
  }

  @Span()
  f2() {
    this.f1();
  }
}
```

current `Span` decorator won't let `f1` be the child of `f2`

Thanks for your help.

**Comment by mentos1386** [comment]
I think i'm having the same issue. In the following example, `OtaQueue.processOtaTaskEvent` should be parent of `OtaQueue.processProcessingStep` but it isn't. They are on the same "level".
![image](https://user-images.githubusercontent.com/1910649/147921617-bf624a5f-1c8e-4cb6-803d-dfe54c3e99f6.png)

This is produced by the following code:
```ts

  @Span()
  async processOtaTaskEvent() {
      return await this.processProcessingStep();
  }

  @Span()
  private async processProcessingStep() {
    // produce IoT.GetOTAUpdate trace span
  }
```

**Comment by pragmaticivan** [comment]
Howdy! I will take a look at it today, sorry about the delay!

**Comment by mentos1386** [comment]
@pragmaticivan no problem. Thanks for working on this in your spare time! And happy new year :)

**Comment by pragmaticivan** [comment]
@mentos1386 I will need to dig a bit more because this seems to only be happening when using standalone classes with no previous instrumentation, right? (ex: Controllers not used)

**Comment by mentos1386** [comment]
@pragmaticivan i cant say if it only happens when not using controllers, but in my case yes.

It's not called by "rest" or "graphql" but it's part of AWS SQS in our case. So there is no instrumentation from controllers,  but there is instrumentation by the aws-sdk (the first two spans on my previous comment with image).
