### ISSUE TITLE
How to pass observation callback to an observableGauge ?

### ISSUE THREAD

**Issue by Djiit** [pragmaticivan/nestjs-otel#171]
Hey there,

it looks like I'm not able to pass a observation callback to the getObservabieGauge method, but only a name and options.

I expect to be able to pass name, options and an observation callback as in https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-sdk-metrics-base/examples/metrics/metrics/observer.js#L27-L33. Is this expected?

Thanks

**Comment by pragmaticivan** [comment]
Fixed, thanks!

**Comment by Djiit** [comment]
That was fast! Thanks!
