### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by pragmaticivan** [pragmaticivan/nestjs-otel#19]

**Comment by issackr** [comment]
Hey, I created PrometheusModule for metrics based on the package and I'm trying to test it but get the error:
Nest can't resolve dependencies of the MetricService (?). Please make sure that the argument OpenTelemetryMeterProvider at index [0] is available in the PrometheusModule context.

this is my module: 
import { Module } from "@nestjs/common";
import { LoggerModule } from "../../logger/logger.module";
import { PrometheusService } from "./prometheus.service";
import { MetricService } from "nestjs-otel";

@Module({
  imports: [LoggerModule],
  providers: [PrometheusService, MetricService],
  exports: [PrometheusService],
})
export class PrometheusModule {}

and my testing module:
  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [PrometheusModule],
      providers: [
        SweetLogger,
        ImageResolver,
        {
          provide: 'METADATA_SERVICE',
          useValue: Image,
        },
      ],
    }).compile();

    resolver = module.get<ImageResolver>(ImageResolver);
  });

but I fail to provide OpenTelemetryMeterProvider whatever I do, I'm not sure how to provide injected stuff.
Will be glad for any help!
Tnx

**Comment by pragmaticivan** [comment]
MetricService is injected globally wehn you use that lib. What you are trying to do is to inject the service rectly into another module without any other dependency being available.

In you main app you need  `OpenTelemetryModule.forRoot(` to be called in your imports for all the dependencies of this service to be available.

Is there a reason you would be creating a prometheus service? MetricService should cover most of the cases, all you need is a prometheus exporter

**Comment by issackr** [comment]
basically you are right but I used interceptor to meter all requests and I noticed that the counters are reset each time if not injected one by one, so I wrapped it with a module that is MetricService alike.

Regarding the error, I added OpenTelemetryModule.forRoot() to my PrometheusModule and now I get another error:
Nest can't resolve dependencies of the OpenTelemetryCoreModule

**Comment by pragmaticivan** [comment]
Hey @issackr could you share more on that issue? when you mean reset each time if not injected, what you mean by that? It should reuse the existing one.

**Comment by issackr** [comment]
@pragmaticivan Sure, it means the counters value aggregators remain on 1 after each call, no matter how many call you make. Regarding the injection I meant like in other libraries which you need to inject each counter your'e using (not generic enough for me), anyway I solved it by wrapping my metric in another map of my own like in MetricService.
I can share the code if you like.
Anyway, do you have any lead how to solve my tests problem about OpenTelemetryCoreModule?

Tnx

**Comment by issackr** [comment]
@pragmaticivan I also migrated my project to nest 8, maybe this is whats making problems

**Comment by pragmaticivan** [comment]
Ohh I haven't tested with nest 8, there might be a problem there indeed.

**Comment by pragmaticivan** [comment]
> basically you are right but I used interceptor to meter all requests and I noticed that the counters are reset each time if not injected one by one, so I wrapped it with a module that is MetricService alike.
> 
> Regarding the error, I added OpenTelemetryModule.forRoot() to my PrometheusModule and now I get another error:
> Nest can't resolve dependencies of the OpenTelemetryCoreModule

I think I found the bug you mentioned while adding more tests today.

https://github.com/pragmaticivan/nestjs-otel/pull/52

**Comment by pragmaticivan** [comment]
`release 1.8.2` should have the fix @issackr

**Comment by issackr** [comment]
@pragmaticivan Looks awesome, thanks for the great work! still having the testing  ModuleRef issue though

**Comment by pragmaticivan** [comment]
@issackr I just fixed the reuse of metrics. I haven't tested on NestJS 8.x yet. They have changed a lot of things. Might need to test a new example this week.

**Comment by pragmaticivan** [comment]
fyi @issackr a lot of the problems I found when I created that lib are going to be fixed in this PR: https://github.com/pragmaticivan/nestjs-otel/pull/55

It will require a Major version though.

**Comment by issackr** [comment]
@pragmaticivan Tnx for the update, I'm definitely gonna use it
