### ISSUE TITLE
Readme not up to date

### ISSUE THREAD

**Issue by CzernyJ** [pragmaticivan/nestjs-otel#192]
Looks like the suggested tracing.ts mentioned in the Readme is not up to date.

`HttpTraceContextPropagator` needs to be  `W3CTraceContextPropagator`
`HttpBaggagePropagator` needs to be  `W3CBaggagePropagator`

`import { BatchSpanProcessor } from '@opentelemetry/tracing';` needs to be `import {BatchSpanProcessor} from '@opentelemetry/sdk-trace-base';`

**Comment by Eroo36** [comment]
It worked for me after making changes according to your comment. Will create a PR to change the README with these changes.

**Comment by pragmaticivan** [comment]
Thanks!! PRs are appreciated. Sorry about the delay, white a hard month for me. ;/

**Comment by pragmaticivan** [comment]
FYI, this full example has the new changes https://github.com/pragmaticivan/nestjs-otel/blob/c11cfa377df82ac8443a5cd95790e6d499b823d8/examples/nestjs-prom-grafana-tempo/src/tracing.ts

**Comment by Peter-Barrett** [comment]
I'm having issues with the initial setup even with those changes, I'm getting ```Type 'BatchSpanProcessor' is not assignable to type 'SpanProcessor'.``` here ` spanProcessor: new BatchSpanProcessor(new JaegerExporter()),`. i have tried using older versions of the libraries with no luck. Does anyone have a solution?

**Comment by Peter-Barrett** [comment]
As always is the way, I found the solution almost immediately after posting. The opentelemetry packages need to be pinned to `<1.1.0` as `1.1.0` isn't compatible with `@opentelemetry/sdk-node` which hasn't been updated yet.

**Comment by pragmaticivan** [comment]
This seems to be fixed now.
