### ISSUE TITLE
Exposing metrics using exporter-colector instead of exporter-prometheus

### ISSUE THREAD

**Issue by mentos1386** [pragmaticivan/nestjs-otel#20]
Currently documentation has this section defined:

```ts
  withPrometheusExporter: {
    enable: true, // Enables prometheus exporter
    withHostMetrics: true, // Includes Host Metrics
    withDefaultMetrics: true, // Includes Default Metrics
    withHttpMiddleware: {  // Includes api metrics
      enable: true,
      timeBuckets: [],
    },
  },
```

Which makes me think that i MUST use prometheus exporter for metrics exporter and can't use something like [@opentelemetry/exporter-collector](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-exporter-collector) instead of it.

To be clear, i would like to use `@opentelemetry/exporter-collector` instead of `@opentelemetry/exporter-prometheus` while still retaining `withHostMetrics: true`, `withDefaultMetrics: true` and `withHttpmiddleware: { enable: true }`.

Something as:
```ts
const OpenTelemetryModuleConfig = OpenTelemetryModule.register({
  metrics: {
    host: true, // Includes Host Metrics
    default: true, // Includes Default Metrics
    http: { // Includes api metrics
       enable: true,
       timeBuckets: [],
     }, 
   },
  nodeSDKConfiguration: {
    metricExporter: new CollectorMetricExporter(), // Define whatever exporter you wish
    spanProcessor: new BatchSpanProcessor(new JaegerExporter()),
    contextManager: new AsyncLocalStorageContextManager(),
    textMapPropagator: new CompositePropagator({
      propagators: [
        new JaegerPropagator(),
        new HttpTraceContextPropagator(),
        new HttpBaggagePropagator(),
        new B3Propagator(),
        new B3Propagator({
          injectEncoding: B3InjectEncoding.MULTI_HEADER,
        }),
      ],
    }),
    instrumentations: [getNodeAutoInstrumentations()],
  },
});
```

**Comment by pragmaticivan** [comment]
I like it, still getting familiar with all the available packages, Hopefully, nobody else is using that package yet, because that change will require a major version

**Comment by pragmaticivan** [comment]
Progress can be followed here: https://github.com/pragmaticivan/nestjs-otel/pull/32

**Comment by pragmaticivan** [comment]
Might need to drop node SDK because it's not very extensible. 

For ref: https://github.com/open-telemetry/opentelemetry-js/issues/2307

**Comment by pragmaticivan** [comment]
@mentos1386 It was released. Sorry about not going Major but I'm assuming nobody is using that yet. 1.4.0 is the release.
