### ISSUE TITLE
Type 'AsyncLocalStorageContextManager' is not assignable to type 'ContextManager'.

### ISSUE THREAD

**Issue by yusef-ho** [pragmaticivan/nestjs-otel#211]
Hello, i have the following issue occured.
<img width="1552" alt="Screen Shot 2022-03-07 at 10 27 13 PM" src="https://user-images.githubusercontent.com/33569998/157052847-51d00fca-e083-4868-89be-c1d51fe9eb61.png">

**Comment by mentos1386** [comment]
@yusef-ho make sure you are using correct versions of all the otel dependencies. https://github.com/open-telemetry/opentelemetry-js#compatibility-matrix

**Comment by pragmaticivan** [comment]
Closing this one. Please comment if you are still getting this error.


Working example: https://github.com/pragmaticivan/nestjs-otel-prom-grafana-tempo
