### ISSUE TITLE
Add custom labels for default and host metrics

### ISSUE THREAD

**Issue by simakwm** [pragmaticivan/nestjs-otel#244]
Fala Ivan, blz?

Is there a way to add custom labels when setting defaultMetrics and/or hostMetrics to `true`?

Thanks in advance.

**Comment by pragmaticivan** [comment]
```ts
const OpenTelemetryModuleConfig = OpenTelemetryModule.forRoot({
  metrics: {
    hostMetrics: true, // Includes Host Metrics
    defaultMetrics: true, // Includes Default Metrics
    apiMetrics: {
      enable: true, // Includes api metrics
      timeBuckets: [], // You can change the default time buckets
      defaultAttributes: {
        // You can set default labels for api metrics
        custom: 'label',
      },
      ignoreRoutes: ['/favicon.ico'], // You can ignore specific routes (See https://docs.nestjs.com/middleware#excluding-routes for options)
      ignoreUndefinedRoutes: false, //Records metrics for all URLs, even undefined ones
    },
  },
});
```
That block:
```ts
defaultAttributes: {
        // You can set default labels for api metrics
        custom: 'label',
      },
```

If that's not working, please open a ticket :D

**Comment by simakwm** [comment]
Thanks for the quick response!
It sets labels only for apiMetrics. Not for hostMetrics or defaultMetrics =/

**Comment by pragmaticivan** [comment]
@simakwm sorry for the delay here. Just double-checked. Both packages to provide these metrics don't support additional labels. Your best bet right now is to relabel your metrics in your own ServiceMonitor if you are using Prometheus Operator or something like that.
