### ISSUE TITLE
How to add Prefix to Metrics

### ISSUE THREAD

**Issue by fuergaosi233** [pragmaticivan/nestjs-otel#265]
I have a lot of applications that are being punctuated and I would like to add prefixes to them, I am currently adding prefixes to each Metrics manually, is there a uniform way to add them? For example, adding the prefix parameter to the Option.

**Comment by pragmaticivan** [comment]
@fuergaosi233 this library does not currently support prefix. I could support it as a property but the underlying libraries would not be able to support that for metrics. ex: https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/opentelemetry-host-metrics/src
