### ISSUE TITLE
Adapt OTel newer version.

### ISSUE THREAD

**Issue by darcydai** [pragmaticivan/nestjs-otel#316]
nestjs-otel is using OTel 1.0.1.  the newest release is 1.5.0. Some APIs and SDK changed a lot.

**Comment by mentos1386** [comment]
@pragmaticivan you mentioned on discord you are making some progress towards this. How are you doing?

I might also have some time to work on this as well.

**Comment by AskAlice** [comment]
+1 to this

**Comment by ruslan-ncg** [comment]
Looks like the are few breaking changes though, is there a list of the working dependencies in the current OTel version?

**Comment by pragmaticivan** [comment]
ref: https://github.com/pragmaticivan/nestjs-otel/pull/321

**Comment by pragmaticivan** [comment]
Working example here: https://github.com/pragmaticivan/nestjs-otel-prom-grafana-tempo
