### ISSUE TITLE
Automatically add Span on every Injectable method, Guards etc.

### ISSUE THREAD

**Issue by mentos1386** [pragmaticivan/nestjs-otel#317]
Could we hook in to @Injectable decorator to automatically discover all classes and their methods. We could then cover them with "@Span" so users wont need to manually add @Span everywhere.

This is implemented by the [@metinseylan/nestjs-opentelemetry](https://github.com/MetinSeylan/Nestjs-OpenTelemetry) as part of [traceAutoInjectors](https://github.com/MetinSeylan/Nestjs-OpenTelemetry/tree/main/src/Trace/Injectors).

**Comment by pragmaticivan** [comment]
@mentos1386 I think the `ideal` place to have something like that is in the actual instrumentation for nestjs. https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-nestjs-core

A lot of it is automatically instrumented in opentelemetry via this plugin and it's compatible with this library already. Extending that kind of work here would duplicate and go against what OpenTelemetry is trying to accomplish.

**Comment by mentos1386** [comment]
Hm yeah. That makes sense. I'll look in to how to do it on the instrumentation level.

**Comment by pragmaticivan** [comment]
Thanks @mentos1386 !

**Comment by VojtechVidra** [comment]
Fixed link for anyone looking at this in the future: https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/instrumentation-nestjs-core
