### ISSUE TITLE
Cannot find module '@opentelemetry/exporter-prometheus' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by laurencefass** [pragmaticivan/nestjs-otel#397]
Im using the configuration from the README to set up my project and the PrometheusExporter is no locatable. However it is included in the package.json as a dependency so I think it should be available. Are missing type definitions causing this error?

i.e. the import 

```
import { PrometheusExporter } from '@opentelemetry/exporter-prometheus';
```

creates the error: 

```
Cannot find module '@opentelemetry/exporter-prometheus' or its corresponding type declarations.ts(2307)
```

however it is included in the package.json file as

```
"@opentelemetry/exporter-prometheus": "^0.34.0",
```

Your inclusion of this nested import appears to be in potential conflict with the advice given in the README which implies the need to install as a separate package

```
Setup
Some peers dependencies are required when some configurations are enabled.
@opentelemetry/exporter-prometheus
```

installing the package separately appears to clear the error but this creates a potential issue with version mismatches. which version are we importing?

Would it be better to remove prometheus exporter to make the package transport agnostic?

**Comment by coler-j** [comment]
It should be listed as a peer dependency, no?

**Comment by laurencefass** [comment]
it was a version specific issue. I aligned all versions correctly and no longer an issue.
