### ISSUE TITLE
Support for nestjs v10?

### ISSUE THREAD

**Issue by PatrickSpies** [pragmaticivan/nestjs-otel#435]
Current version of nestjs-otel does not support nestjs v10:

> npm ERR! Found: @nestjs/common@10.0.1
> npm ERR! node_modules/@nestjs/common
> npm ERR!   @nestjs/common@"10.0.1" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @nestjs/common@"^9.0.0" from nestjs-otel@5.1.2
> npm ERR! node_modules/nestjs-otel
> npm ERR!   nestjs-otel@"5.1.2" from the root project

peerDependencis defined at package.json:
```json
  "peerDependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0"
  },
```

Are there any plans for supporting nestjs v10? Installing packages with `--force` seems to work, we are not seeing any issues..

**Comment by pragmaticivan** [comment]
Yes, down to support v10, PRS are always welcome.
