### ISSUE TITLE
Breaking changes 5.1.3 | Cannot use with nest v9

### ISSUE THREAD

**Issue by MaksimKiselev** [pragmaticivan/nestjs-otel#442]
I see that support for v10 was be added here:
https://github.com/pragmaticivan/nestjs-otel/commit/87bb30e7f8d7a987f584acbf28aaf0bab00e12c7

After support for v9 has dropped here
https://github.com/pragmaticivan/nestjs-otel/commit/d27a3e09b268442c0c444f9814fd8e791aa26d19

5.1.3 is patch release, but why hard dropped support for v9?

Workaroud for v9 users:
Set exact version 5.1.2 for nest-otel in package.json
```
"nestjs-otel": "5.1.2",
```

**Comment by pragmaticivan** [comment]
Fix released https://github.com/pragmaticivan/nestjs-otel/pull/441
