### ISSUE TITLE
Prometeus metric cluster aggregation

### ISSUE THREAD

**Issue by HarshRatel** [pragmaticivan/nestjs-otel#452]
I run my nestjs app in cluster mode by using nodejs:cluster. We used prom-client to collect metrics. By using AggregatorRegistry i managed to collect metrics from each application cluster instance. We want to change our monitoring to nestjs-otel for future monitoring settings.

```
const { endpoint, metricPort } = { endpoint: '/metrics', metricPort: 3002 };
const otelSDK = new NodeSDK({
  // spanProcessor: new BatchSpanProcessor(new JaegerExporter()),
  metricReader: new PrometheusExporter({ endpoint, port: metricPort }, () => {
    console.log(
      `prometheus scrape endpoint: http://localhost:${metricPort}${endpoint}`,
    );
  }),
  // traceExporter: new ConsoleSpanExporter(),
  contextManager: new AsyncLocalStorageContextManager(),
  textMapPropagator: new CompositePropagator({
    propagators: [
      new W3CTraceContextPropagator(),
      new W3CBaggagePropagator(),
      new B3Propagator(),
      new B3Propagator({
        injectEncoding: B3InjectEncoding.MULTI_HEADER,
      }),
    ],
  }),
  instrumentations: [
    new FastifyInstrumentation(),
    getNodeAutoInstrumentations(),
  ],
});

otelSDK.start();

if (process.env.NODE_ENV === 'dev') {
  bootstrap();
} else {
  runInCluster(bootstrap);
}
```

When I run my app in dev mode, all metrics work fine. But when i run application in production mode, API metrics are not collected. Is it possible to collect metrics from different application instances in one place and get them from http server?

**Comment by pragmaticivan** [comment]
Afaik this is not supported by OTEL `yet` https://github.com/open-telemetry/opentelemetry-js/issues/1252

Your best bet is to use OTLP With a otel collector instead, that way you would not need to scrape your app for metrics.

**Comment by pragmaticivan** [comment]
Ref: https://www.npmjs.com/package/@opentelemetry/exporter-metrics-otlp-http
