### ISSUE TITLE
How to track gRPC requests?

### ISSUE THREAD

**Issue by gigi** [pragmaticivan/nestjs-otel#494]
Hello.
Could you please provide an example how this module can help to collect gRPC endpoints' metrics.

Thank you

**Comment by pragmaticivan** [comment]
This is more of a opentelemetry question: https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-node

^ if you use auto instrumentations, grpc is included automatically.

ex: https://github.com/pragmaticivan/nestjs-otel-prom-grafana-tempo/blob/main/services/actor/src/instrumentation.ts#L31

**Comment by gigi** [comment]
Yes. 
@pragmaticivan thanks for your reply.

We use `GrpcInstrumentation` for traces, but it doesn't add any metrics to exporters like described here 
https://github.com/pragmaticivan/nestjs-otel?tab=readme-ov-file#api-metrics-with-middleware

It seems that `apiMetrics.enable: true` works only for http (not Nest microservice) endpoints, right? So there is no way to do it automatically.

**Comment by pragmaticivan** [comment]
Ohhh I see, no, se don't instrument grpc as part of this lib like we do with REST because there were no settled conventions in opentelemetry yet

**Comment by pragmaticivan** [comment]
Note that you can simply implement a middleware yourself and set metrics as you see fit for grpc

**Comment by gigi** [comment]
Ok
Thank you!

**Comment by pragmaticivan** [comment]
I will keep an eye and check if they finally had established a semantic convention for metric names and attributes soon

**Comment by abdullah-retorio** [comment]
Hello, thank you for this nice library, 

This issue is closed, but is there any update on this:

>  I will keep an eye and check if they finally had established a semantic convention for metric names and attributes soon
