### ISSUE TITLE
Version 2.2.0 is not compatible with NestJS 7.x

### ISSUE THREAD

**Issue by pratimsc** [pragmaticivan/nestjs-otel#81]
The version 2.2.0 requires npm packages from NestJs version 8.x.

This forces the application developed using NestJS 7.x to use `--legacy-peer-deps`. 

Could the library be updated to support both NestJS 7.x and NestJS 8.x

**Comment by pragmaticivan** [comment]
@pratimsc yeah, PRs are welcome. I agree with your concern. Might take a look soon

**Comment by pratimsc** [comment]
I am not a NestJS expert :) . But let me try making changes and creating a PR.

**Comment by pragmaticivan** [comment]
Might need to make the nestJS libs peer dependency but something like `"react": "^15.0.0 || ^16.0.0",` should probably cover that in the package.json

**Comment by pragmaticivan** [comment]
https://github.com/pragmaticivan/nestjs-otel/blob/main/package.json#L75-L76 Just need to apply the same pattern on those 2 lines.

**Comment by pratimsc** [comment]
@pragmaticivan - I have submitted a pull request, please review and merge if you are happy with changes.

**Comment by pratimsc** [comment]
What needs to be done to release this merge as `v2.2.1`

**Comment by pratimsc** [comment]
@pragmaticivan - The review comments implemented. 
And a new change was introduced, to overcome a run-time error reported by NestJS 7 based applications, during testing at my end.

**Comment by pragmaticivan** [comment]
Pr merged.
