### ISSUE TITLE
Question: Installation issues

### ISSUE THREAD

**Issue by cramhead** [pragmaticivan/nestjs-otel#85]
I'm trying to integrate your package into an existing Nestjs 7 app. I've basically copied and pasted the example from the readme, but it seems to fail when I attempt to get a span. I'm very new to OpenTelemetry so can't really say I have much of a conceptual model to support debugging. 

The code that generates the error is from the readme example
![image](https://user-images.githubusercontent.com/386035/129944974-099d4e20-ffb2-4b91-8095-7c0239550b6f.png)
and lower down
![image](https://user-images.githubusercontent.com/386035/129945117-f4ff4131-2535-4690-acf5-8e18b4e48c64.png)

The currentSpan is undefined resulting in the addEvent failing
```
{"level":50,"time":1629306567682,"pid":111,"hostname":"a68e9c9c5b3c","req":{"id":"dcaa44df-0249-4f43-b9ad-1948dfa74b1b","method":"POST","url":"/api/v3/authenticate","remoteAddress":"::ffff:172.28.0.3","remotePort":53100},"logId":"11fd25fa-8aec-4762-a06c-f2f15c11e0c1","context":"ExceptionsHandler","trace":"TypeError: Cannot read property 'addEvent' of undefined\n    at AuthenticationService.authenticationFinalization (/usr/src/app/dist/identity/apis/authentication/authentication.service.js:71:21)\n    at /usr/src/app/node_modules/nestjs-otel/lib/tracing/decorators/span.js:14:35\n    at NoopContextManager.with (/usr/src/app/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:36:24)\n    at ContextAPI.with (/usr/src/app/node_modules/@opentelemetry/api/build/src/api/context.js:71:54)\n    at AuthenticationService.PropertyDescriptor (/usr/src/app/node_modules/nestjs-otel/lib/tracing/decorators/span.js:11:38)\n    at AuthenticationController.authenticateWithUsernameAndPassword (/usr/src/app/dist/identity/apis/authentication/authentication.controller.js:46:64)\n    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29","msg":"Cannot read property 'addEvent' of undefined"}
```

When stepping into the `traceService.getSpan` I can see that _currentContext map is empty
![image](https://user-images.githubusercontent.com/386035/129944335-4bef7719-679e-42e0-8c7f-14538158deb4.png)

Any thoughts on what may not be correct?

Many thanks for making this package and the time to review this message.

**Comment by pragmaticivan** [comment]
hi @cramhead could you provide some insight on your trace.ts + nestjs-otel setup? I've just tested everything you posted here in the example. It works. Did you end up setting up the trace file like in the example?

**Comment by pragmaticivan** [comment]
I will push my example changes in a few min.

**Comment by pragmaticivan** [comment]
<img width="1910" alt="Screen Shot 2021-08-18 at 8 30 29 PM" src="https://user-images.githubusercontent.com/301291/129993343-b33fd068-c0ed-4fd2-84ab-951891e4616d.png">
Example of a custom span I created

**Comment by cramhead** [comment]
Hi @pragmaticivan,

Thanks for helping. 
The `trace.ts`. Note: commented to process import as it was causing an error. Otherwise, it's a direct copy and paste from the readme The shutdown does log correctly.
```
import {
    CompositePropagator,
    HttpTraceContextPropagator,
    HttpBaggagePropagator,
} from '@opentelemetry/core';
import { BatchSpanProcessor } from '@opentelemetry/tracing';
import { JaegerExporter } from '@opentelemetry/exporter-jaeger';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { JaegerPropagator } from '@opentelemetry/propagator-jaeger';
import { B3InjectEncoding, B3Propagator } from '@opentelemetry/propagator-b3';
import { PrometheusExporter } from '@opentelemetry/exporter-prometheus';
import { NodeSDK } from '@opentelemetry/sdk-node';
import { AsyncLocalStorageContextManager } from '@opentelemetry/context-async-hooks';
// import * as process from 'process'; removed as TypeError: process.on is not a function

const otelSDK = new NodeSDK({
    metricExporter: new PrometheusExporter({
        port: 8081,
    }),
    metricInterval: 1000,
    spanProcessor: new BatchSpanProcessor(new JaegerExporter()),
    contextManager: new AsyncLocalStorageContextManager(),
    textMapPropagator: new CompositePropagator({
        propagators: [
            new JaegerPropagator(),
            new HttpTraceContextPropagator(),
            new HttpBaggagePropagator(),
            new B3Propagator(),
            new B3Propagator({
                injectEncoding: B3InjectEncoding.MULTI_HEADER,
            }),
        ],
    }),
    instrumentations: [getNodeAutoInstrumentations()],
});

export default otelSDK;
// You can also use the shutdown method to gracefully shut down the SDK before process shutdown
// or on some operating system signal.
process.on('SIGTERM', () => {
    otelSDK
        .shutdown()
        .then(
            () => console.log('SDK shut down successfully'),
            (err) => console.log('Error shutting down SDK', err),
        )
        .finally(() => process.exit(0));
});
```

The tracing.ts is imported and otelSDK.start is tied into the boot sequence. We have multiple mains so previously i had missed one. Fixed now.
![image](https://user-images.githubusercontent.com/386035/130121694-6544094d-6fda-4700-8eb7-b0d20b43860b.png)

The config in the app.module. Note we were already using prom-client
![image](https://user-images.githubusercontent.com/386035/130122127-c37012e5-533e-414a-b8df-865b52f05019.png)

In my authenticationService the traceService is populated. I have a method decorated with `@Span` and a call to the traceService to getSpan
![image](https://user-images.githubusercontent.com/386035/130123107-7d11fae2-acca-4d8d-bba4-147d0eba5932.png)

When debugging the getSpan call I can see the _context is set
![image](https://user-images.githubusercontent.com/386035/130121184-96c44283-aba7-44b4-a393-deb5a5e4cfac.png)

TypeScript complains that contextManager is incompatible. Could that be the problem?
![image](https://user-images.githubusercontent.com/386035/130122355-202c7c18-3987-4364-85a8-de56810af35c.png)

**Comment by cramhead** [comment]
> <img alt="Screen Shot 2021-08-18 at 8 30 29 PM" width="1910" src="https://user-images.githubusercontent.com/301291/129993343-b33fd068-c0ed-4fd2-84ab-951891e4616d.png">
> 
> Example of a custom span I created `findOne Section`

Super cool screenshot. I'm looking forward to seeing this too

**Comment by pragmaticivan** [comment]
@cramhead would you by any chance be on NestJS Discord? might be faster if I help you through messages and maybe a quick pair prog.

**Comment by cramhead** [comment]
I've used Discord, but really only as a message board. It would be great if we could pair program some. My user is marc.dentremont#5299

**Comment by pragmaticivan** [comment]
Closing as you got it working, thanks!
